### ISSUE TITLE
The test results do not match with officially shown results.

### ISSUE THREAD

**Issue by coreqode** [zju3dv/animatable_nerf#12]
Hi, This is very awesome work. 

However, I am not able to get similar results to the official ones shown in the paper, when I tried to test myself on the "386" folder. The results are very noisy. Do you post-process the results as well?

<img width="748" alt="image" src="https://user-images.githubusercontent.com/18486587/150266123-eeb0ce38-f700-4d65-976a-b33a9c5dc06f.png">

**Comment by pengsida** [comment]
I did not show the reconstructed geometries of "386" in the paper.
Its reconstruction results are noisy.
