### ISSUE TITLE
Question about the last value of skinning weights in canonical/observation space

### ISSUE THREAD

**Issue by taconite** [zju3dv/animatable_nerf#13]
Hi, 

First thanks for the nice code&paper!

I am trying to use your code on our own data. One thing I noticed is that the observation/canonical skinning weights (stored in lbs/bweights as well as in lbs/tbw.npy) are pre-computed and their last dimension has 25 values. Since original SMPL skinning weights have only 24 values, my question is that how exactly is this 25th value defined and how could I compute it properly?

thanks in advance!

**Comment by pengsida** [comment]
It is the distance to the smpl surface: https://github.com/zju3dv/animatable_nerf/blob/master/tools/prepare_blend_weights.py#L270
