### ISSUE TITLE
关于使用custom dataset

### ISSUE THREAD

**Issue by wkMvg** [zju3dv/animatable_nerf#16]
hi，
思达你好，非常感谢工作的开源。
我想请问下关于如何使用自己的数据进行训练，如何进行数据处理，有没有相关的文档可以提供呢？非常感谢

**Comment by pengsida** [comment]
我没有写文档。可以参考我们开源的数据进行数据格式的组织。
这里有一部分可以用的代码：
1. Motion capture: https://github.com/zju3dv/EasyMocap
2. Preparing blend weights: https://github.com/zju3dv/animatable_nerf/blob/master/tools/prepare_blend_weights.py

**Comment by wkMvg** [comment]
好的 非常感谢
