### ISSUE TITLE
from psbody.mesh import Mesh

### ISSUE THREAD

**Issue by caiyongqi** [zju3dv/animatable_nerf#18]
Hi. I have installed [meshlite](https://github.com/MPI-IS/meshlite), but still get the bug.
```
from psbody.mesh import Mesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mesh
```
In prepare_blend_weights.py.

**Comment by pengsida** [comment]
Install this: https://github.com/MPI-IS/mesh
