### ISSUE TITLE
RuntimeError: cuDNN error / cannot join current thread

### ISSUE THREAD

**Issue by 3DebbieChen9** [zju3dv/animatable_nerf#19]
While I was trying to visualize novel views of the 0-th frame on Human3.6M.
I encountered the following error...
<img width="1207" alt="cuDNN error" src="https://user-images.githubusercontent.com/58079945/165077988-16769669-3920-480f-a15b-0bd753a53962.png">
My setup is,
- Ubuntu: 20.04.4
- CUDA: 10.1
- torch: v1.4.0
<img width="468" alt="cuda version" src="https://user-images.githubusercontent.com/58079945/165078053-6c5e90a7-3aee-47e4-b0ad-7be39d4962a3.png">

Is that neccesary to use CUDA 10.0 to run animatable_nerf?

Thank you.

**Comment by pengsida** [comment]
Maybe the cuda of pytorch does not match with the system cuda.

**Comment by 3DebbieChen9** [comment]
But I was following the PyTorch official documentation to install the torch
![image](https://user-images.githubusercontent.com/58079945/165080118-b42fbddc-448a-4f44-97d5-83ec5d7064d2.png)
The version of pytorch and the system cuda should be a match??
