### ISSUE TITLE
关于People_snapshot 测试

### ISSUE THREAD

**Issue by zhangchenxu528** [zju3dv/animatable_nerf#22]
你好，非常感谢开源优秀的工作。文章中使用的数据集都是多角度视频，请问作者有在单相机视频上面进行过测试吗？ 我在People_snapshot上面训练，并且进行novel view测试，结果不太理想，下面是我的一些测试结果。
![0009](https://user-images.githubusercontent.com/92286174/165374718-6370311e-bdbb-46cb-9bb5-af5957ce68d2.png)
![0030](https://user-images.githubusercontent.com/92286174/165374775-52bf7ab2-02e2-4d10-9166-2bde899ccb04.png)
![0058](https://user-images.githubusercontent.com/92286174/165374787-a52c5d01-8b78-47ed-96a2-200229fed2f7.png)
![0114](https://user-images.githubusercontent.com/92286174/165374796-fa35e24b-686f-492c-9343-b899ba89401c.png)
![0135](https://user-images.githubusercontent.com/92286174/165374812-b62c3d93-1b34-445f-958a-0cd4b2644b7a.png)

这个结果和neural body区别很大，希望作者可以帮我分析一下原因。十分感谢！

**Comment by pengsida** [comment]
原因是people snapshot的human pose不准确. 而Animatable NeRF很依赖human pose的准确度, 这一点在论文里有分析.
