### ISSUE TITLE
joints.npy does not exist in data/zju_mocap/CoreView_313\\lbs\\joints.npy

### ISSUE THREAD

**Issue by takealook00** [zju3dv/animatable_nerf#26]
Hello, Sir. I am trying to  the test on 313 but i got error: FileNotFoundError: [Errno 2] No such file or directory: 'data/zju_mocap/CoreView_313\\lbs\\joints.npy'. Could you give me advice how to get joints.npy?

**Comment by pengsida** [comment]
Did you correctly set the path?

**Comment by takealook00** [comment]
> Did you correctly set the path?
yes, but Jjust for make sure, is joints.npy supposed to be in the processed ZJU-MoCap dataset folder? Because I have only bweights folder in the zhu_mocap/CoreView_313/lbs.

**Comment by takealook00** [comment]
Yes I did

**Comment by Mumuwei** [comment]
I have the same problem, how did you solve it？

**Comment by pengsida** [comment]
Did you correctly set the path or use the correct version of ZJU-MoCap.
There is a ZJU-MoCap data that is specifically processed for animatable nerf.

**Comment by takealook00** [comment]
I do not know why exactly but whenever I downloaded CoreView_313 dataset or any dataset, the folder 'lbs' was missed or something missed. I guess this could be my disk storage problem or the way I extracted the file.
Therefore, during the process of downlading and extracting dataset, I should check it if it exists. I solved it like this way.

**Comment by Mumuwei** [comment]
> 

Thanks, I will check it out.

**Comment by takealook00** [comment]
@@

> > 
> 
> Thanks, I will check it out.
Hey, Have u solved it?

**Comment by Mumuwei** [comment]
> @@
> 
> > > 
> > 
> > 
> > Thanks, I will check it out.
> > Hey, Have u solved it?

Solved, I downloaded an inappropriate dataset.  Thanks a lot.

**Comment by takealook00** [comment]
> > @@
> > > > 
> > > 
> > > 
> > > Thanks, I will check it out.
> > > Hey, Have u solved it?
> 
> Solved, I downloaded an inappropriate dataset. Thanks a lot.

Which dataset did u download to solve? because it happened again lol.

**Comment by takealook00** [comment]
> > @@
> > > > 
> > > 
> > > 
> > > Thanks, I will check it out.
> > > Hey, Have u solved it?
> 
> Solved, I downloaded an inappropriate dataset. Thanks a lot.

lbs was supposed to be in the dataset , isn't it?

**Comment by Mumuwei** [comment]
> > > @@
> > > > > 
> > > > 
> > > > 
> > > > Thanks, I will check it out.
> > > > Hey, Have u solved it?
> > 
> > 
> > Solved, I downloaded an inappropriate dataset. Thanks a lot.
> 
> lbs was supposed to be in the dataset , isn't it?

This is the link of ZJU-MoCap dataset for Animatable NeRF provided by the authors.
https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/EsCahURVXs1Gm6Oe-sF9zFABWwOLblFd_dP0Ovh8NN2d9w?e=L8P7B0

**Comment by takealook00** [comment]
> > > > @@
> > > > > > 
> > > > > 
> > > > > 
> > > > > Thanks, I will check it out.
> > > > > Hey, Have u solved it?
> > > 
> > > 
> > > Solved, I downloaded an inappropriate dataset. Thanks a lot.
> > 
> > 
> > lbs was supposed to be in the dataset , isn't it?
> 
> This is the link of ZJU-MoCap dataset for Animatable NeRF provided by the authors. https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/EsCahURVXs1Gm6Oe-sF9zFABWwOLblFd_dP0Ovh8NN2d9w?e=L8P7B0

Thank you so much. Can I give u my email adress? its mxc@student.bham.ac.uk.

**Comment by Mumuwei** [comment]
> > > > > @@
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > Thanks, I will check it out.
> > > > > > Hey, Have u solved it?
> > > > 
> > > > 
> > > > Solved, I downloaded an inappropriate dataset. Thanks a lot.
> > > 
> > > 
> > > lbs was supposed to be in the dataset , isn't it?
> > 
> > 
> > This is the link of ZJU-MoCap dataset for Animatable NeRF provided by the authors. https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/EsCahURVXs1Gm6Oe-sF9zFABWwOLblFd_dP0Ovh8NN2d9w?e=L8P7B0
> 
> Thank you so much. Can I give u my email adress? its [mxc@student.bham.ac.uk](mailto:mxc@student.bham.ac.uk).

Ok. yangquanwei@mail.ustc.edu.cn

**Comment by pengsida** [comment]
@Mumuwei Do not share the dataset link publicly.

**Comment by Mumuwei** [comment]
> @Mumuwei Do not share the dataset link publicly.

Sorry, I got it.
