### ISSUE TITLE
cannot find the results which were supposed to be located at data/novel_view/aninerf_313

### ISSUE THREAD

**Issue by takealook00** [zju3dv/animatable_nerf#27]
Hello, Sida. 
I have been trying to visualise 313 in ZJU-MoCap but I cant see any result in the folder.  Am I missing something? Is it a path problem? 

I am pretty sure with setting path correctly.

And one more thing, is it normal to have "The syntax of the command is incorrect."?
![Capture](https://user-images.githubusercontent.com/40441643/174504724-42ccce41-9f35-45e0-b992-623e19595628.PNG)

**Comment by pengsida** [comment]
It seems that you are using the Windows system.
Maybe the command does not work on the Windows system: https://github.com/zju3dv/animatable_nerf/blob/master/lib/visualizers/if_nerf.py#L35
