### ISSUE TITLE
Segmentation Fault(core dumped) error

### ISSUE THREAD

**Issue by iseunghoon** [zju3dv/animatable_nerf#29]
Hello
I tried to run your code but I get error message... "Segmentation Fault (core dumped)"

I used pytorch==1.11.0, CUDA 11.3, torchvision 0.12.0..

Is your code only available in pytorch 1.4.0 & CUDA 10 version?

**Comment by dendenxu** [comment]
Hi, thanks for trying out our code!

**Comment by iseunghoon** [comment]
I resolved the problem after changing pytorch version. Works well!! Thank you!!

**Comment by iseunghoon** [comment]
Thank you for notifying me. I fixed the issue. Maybe the codes are crushed
because of compatibility of pytorch version and CUDA version.

=============================================



SEUNGHOON LEE

Integrated MS/Ph.D  in MVP Lab, Yonsei University.

------------------------------

LAB 02-2123-7843 Mobile 010-5523-9737

Web github.com/iseunghoon

Email ***@***.***

Yonsei University 50 Yonsei-ro, Seodaemun-gu,

Seoul 03722, Republic of Korea
=============================================


2022년 7월 15일 (금) 오전 1:59, Zhen Xu ***@***.***>님이 작성:
