### ISSUE TITLE
Where can I find the implementation of the CNN renderer described in AniSDF?

### ISSUE THREAD

**Issue by jasongzy** [zju3dv/animatable_nerf#30]
It seems that the current released version of AniSDF does not contain a 2D neural renderer. Did I miss something?

**Comment by pengsida** [comment]
Yes, it does not include the 2D neural renderer.

**Comment by jasongzy** [comment]
Thanks for your reply!
Any plans to release the code of 2D neural renderer?

**Comment by pengsida** [comment]
Currently we do not plan to release the code of 2D neural renderer. The pipeline is too long, making the training not elegant.

**Comment by jasongzy** [comment]
Got it. Thanks.
