### ISSUE TITLE
questions about how to process H3.6m (lbs/bweights/*.npy)

### ISSUE THREAD

**Issue by longxiang-ai** [zju3dv/animatable_nerf#32]
when loading human3.6m dataset, here comes a question that I can't change the batch_size from 1 to any other number > 1. Then I find out that it's because when loading data, the size of the param "pbw" changes as well. The pbw is loaded in the lbs/bweights folder, which is provided by you. I wanna process more other datasets, what should I do? How to make this pbw blend weights have the same size(n_batch,d,h,w,25)? @pengsida

**Comment by pengsida** [comment]
The script for generating blend weights: https://github.com/zju3dv/animatable_nerf/blob/master/tools/prepare_blend_weights.py

Or you could revise the collator of pytorch: https://discuss.pytorch.org/t/how-to-use-collate-fn/27181/5

**Comment by chaneyddtt** [comment]
Hi @pengsida, seems that the link for generating blend weights does not exist. Could you pls provide the updated link?

**Comment by dendenxu** [comment]
@chaneyddtt Sorry for the late reply, we've updated the code structure so the link is deprecated.
Here's the location for the new script: https://github.com/zju3dv/animatable_nerf/blob/master/tools/custom_dataset/prepare_blend_weights.py
Permlink: https://github.com/zju3dv/animatable_nerf/blob/438f12e95230c53fc3a544801c68d65c23de8752/tools/custom_dataset/prepare_blend_weights.py

**Comment by chaneyddtt** [comment]
Thanks a lot for your reply! @dendenxu

**Comment by chaneyddtt** [comment]
Hi @dendenxu, I have another question. The provided blend weights is generated from the old params or the new params?
