### ISSUE TITLE
how to get human3.6 annots.npy?

### ISSUE THREAD

**Issue by daixiangzi** [zju3dv/animatable_nerf#36]

**Comment by pengsida** [comment]
You could learn about the data format of `annots.npy` and then reorganize the data of Human3.6.

**Comment by daixiangzi** [comment]
ok ,thank you

**Comment by daixiangzi** [comment]
> You could learn about the data format of `annots.npy` and then reorganize the data of Human3.6.

can you give me a example ?

**Comment by pengsida** [comment]
You could use the ZJU-MoCap dataset as an example.

**Comment by dendenxu** [comment]
> > You could learn about the data format of `annots.npy` and then reorganize the data of Human3.6.
> 
> can you give me a example ?

You could also checkout [this issue](https://github.com/zju3dv/animatable_nerf/issues/35) and refer to [this guide in neuralbody](https://github.com/zju3dv/neuralbody/tree/master/tools/custom) for a more detailed illustration.

**Comment by daixiangzi** [comment]
Ok，thank



我没有什么天赋，我只是生而由来的执着。


------------------ Original ------------------
From: pengsida ***@***.***&gt;
Date: Wed,Aug 3,2022 10:23 PM
To: zju3dv/animatable_nerf ***@***.***&gt;
Cc: daixiangzi ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [zju3dv/animatable_nerf] how to get human3.6 annots.npy? (Issue #36)





 
You could use the ZJU-MoCap dataset as an example.
