### ISSUE TITLE
dataset about animatable sdf 

### ISSUE THREAD

**Issue by yjh576** [zju3dv/animatable_nerf#38]
According to your readme, I directly run the training code for animatable sdf on human36. This reports an error, i.e., no such file or directory: 'data/h36m/S9/Posing/lbs/weights.npy'. 

I don't find weights.npy in the corresponding directory under human36 datasets. Do I need to additionally generate this weights.npy ?

**Comment by takealook00** [comment]
I have same issue. Have u solved it?

**Comment by dendenxu** [comment]
Hi, thanks again for the feedback.
We've updated the datasets to fix this, please email [pengsida@zju.edu.cn](mailto:pengsida@zju.edu.cn) for the updated links.

**Comment by tpzou** [comment]
Hi, @dendenxu. How can I generate the 'weights.npy' by myself data?
