### ISSUE TITLE
AttributeError: 'Network' object has no attribute 'get_alpha'

### ISSUE THREAD

**Issue by LaolangOne** [zju3dv/animatable_nerf#39]
python run.py --type visualize --cfg_file configs/aninerf_313.yaml exp_name aninerf_313 vis_posed_mesh True
The following error occurs when running the above statement。
AttributeError: 'Network' object has no attribute 'get_alpha'

**Comment by takealook00** [comment]
have same error. Have u solved it?

**Comment by dendenxu** [comment]
Hi, thanks for the feedback!
This bug should have been fixed in the [latest commit](https://github.com/zju3dv/animatable_nerf/commit/c8b9a140d032a70a6e0e428c1e03aa39e9c95980).
