### ISSUE TITLE
Surface-guided rendering of AniSDF

### ISSUE THREAD

**Issue by wenbin-lin** [zju3dv/animatable_nerf#41]
Thanks for sharing the code. 
It seems that the surface-guided rendering of AniSDF is not implemented in the code. Did I miss something?

**Comment by dendenxu** [comment]
Thanks for checking out our code!
Currently we have no plan to open-source that section of the original AniSDF paper in this repository.
This repo is for [animable_nerf](https://arxiv.org/abs/2105.02872) and the [extended version of animatable_nerf](https://arxiv.org/abs/2203.08133).
