### ISSUE TITLE
visualize blend weight

### ISSUE THREAD

**Issue by Andyen512** [zju3dv/animatable_nerf#42]
Hi Sida，
I'd like to ask how can I visual the initial blend weight or the learned blend weight?

**Comment by dendenxu** [comment]
Hi Andy,

Currently we haven't included such functionality in this repo.

But I think this visualization will indeed be quite interesting. I would suggest looking into the volume format .vdb and exporting the sampled blend weight field in such format, encoding different activations with different colors if you're interested in implementing it.

**Comment by Andyen512** [comment]
Is there any repo related to this? I'm not familiar but I'm interested to implement it.

**Comment by dendenxu** [comment]
Hi!

Maybe you can check out [openvdb](https://github.com/AcademySoftwareFoundation/openvdb) and it's related python interface for the vdb format. 

But it's just my suggestion! Feel free to explore other possibilities, like storing the weight field in a regular point cloud grid or simply render an image of a slice of the blend weight field in our existing pipeline.

And by encoding the weight associations with colors I'd like to refer you to [scanimate](https://github.com/shunsukesaito/SCANimate) for their cool visualizations.

Feel free to contribute!
