### ISSUE TITLE
latent code

### ISSUE THREAD

**Issue by LaolangOne** [zju3dv/animatable_nerf#43]
What is the meaning of the 'latent codes'? There is no detailed introduction to its origin and meaning in the paper.

**Comment by dendenxu** [comment]
The notion of latent codes in Animatable NeRF is borrowed from Neural Body (where they're denoted latent embedding).

In the Neural Body paper, they refer to the latent embedding as inspired by the auto decoder structure in DeepSDF.

**Comment by LaolangOne** [comment]
> The notion of latent codes in Animatable NeRF is borrowed from Neural Body (where they're denoted latent embedding).
> 
> In the Neural Body paper, they refer to the latent embedding as inspired by the auto decoder structure in DeepSDF.

I see, thank you for your reply.
