### ISSUE TITLE
confused about the yaml files

### ISSUE THREAD

**Issue by liwenssss** [zju3dv/animatable_nerf#45]
hello I read your paper in ICCV 2021 and newly pre-print paper. I am confused about the experiment settings. In paper "Animatable Implicit Neural Representations for Creating Realistic Avatars from Videos":
1.Section 3.2.1 describe the method in the ICCV2021 paper and its corresponding config file is configs/aninerf_s9p.yaml
2.Section 3.2.2 's config file is configs/aligned_nerf_pdf/aligned_aninerf_pdf_s9p.yaml(termed pdf)
3.the config file of "pdf+sdf" is configs/sdf_pdf/anisdf_pdf_s9p.yaml
am I right?
and I dont know what the config file configs/aligned_nerf_lbw/aligned_aninerf_lbw_s9p.yaml refer to ...

**Comment by dendenxu** [comment]
Hi! Sorry for the confusion. We retain both the configuration files for the ICCV and pre-print papers. And you're right about the correspondence between configuration files and methods.

Configurations like `configs/aninerf_s9p.yaml` are legacy configuration files to use if you want to reproduce the ICCV paper. And `configs/aligned_nerf_lbw/aligned_aninerf_lbw_s9p.yaml` is to be used if you're interested in the pre-print paper.

These two indeed refer to the same method (as you've mentioned it in `1.`). However there exist some implementation detail differences between the two versions from the ICCV paper and pre-print one. Thus we created to separate configuration files for them.

Will this clear out the confusion?

**Comment by liwenssss** [comment]
Tanks for your explain. Nice work!
