### ISSUE TITLE
When install the libraries pointnet2 and PCPR to run NHR and NT, some errors occur:

### ISSUE THREAD

**Issue by XuqianRen** [zju3dv/animatable_nerf#49]
Hi, when I want to install the pointnet2 and PCPR libraries to run the code in your project, I met these problems:
1. Although I had installed the pointnet2 successfully, when I run the code, it occurred this error:

![image](https://user-images.githubusercontent.com/84827495/197338226-65a6faab-95b1-492c-bcac-2e993b674e8f.png)

2. When I try to install the PCPR, I can't install it successfully.
![image](https://user-images.githubusercontent.com/84827495/197338210-dc1244fb-b23d-4e24-87a8-7b66ee4e73fe.png)

How can I install them and run the code successfully? Thanks.

**Comment by pengsida** [comment]
Please install Python 3.7 and torch==1.4.0+cu100, and then try it.

![image](https://user-images.githubusercontent.com/11582122/228879863-2cce70a6-fd86-4543-8dd0-50076faa1838.png)
