### ISSUE TITLE
AniSDF gives noisy mesh in observation space for ZJU-mocap dataset

### ISSUE THREAD

**Issue by HelloRicky123** [zju3dv/animatable_nerf#51]
Hi,

I trained the AniSDF on ZJU-mocap 387 sequence with `configs/sdf_pdf/anisdf_pdf_387.yaml`.  I then produce mesh with `python run.py --type visualize --cfg_file configs/sdf_pdf/anisdf_pdf_387.yaml exp_name anisdf_pdf_387 vis_posed_mesh True resume True`. However the reconstructed mesh seems noisy.

- Reconstructed mesh for 387 sequence
<img width="200" alt="image" src="https://user-images.githubusercontent.com/25146499/198875676-8535b719-5de3-4d5e-966c-2c93fc64a7ed.png">

I found if I omit in `lib/networks/renderer/sdf_mesh_renderer.py` the following lines, the mesh is smooth.
```
if 'gradient_of_deformed_sdf' in dir(self.net):
    normal, sdf = self.batchify_normal_sdf(pts, batch)
    resd = -normal * sdf
    resd = torch.from_numpy(resd).to(pts)
    deformed_pts = pts + resd
else:
    deformed_pts = pts
```

- Reconstructed mesh without offset for mesh vertices.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/25146499/198875776-e4074fdd-ebe6-4bab-a74e-40cf1def5d9a.png">

Could you provide any suggestions to solve this problem?

Thanks a lot.

**Comment by dendenxu** [comment]
Hi, we've implemented a fix in the newest commit. Could you test whether the mesh is clean and residual deformation looks reasonable now?

**Comment by HelloRicky123** [comment]
Thanks for such a quick response. I test it and the reconstructed mesh seems reasonable.
