### ISSUE TITLE
Is there any way that I can color the model I've generated?

### ISSUE THREAD

**Issue by Marianoeli** [zju3dv/animatable_nerf#53]
Thanks for your amazing work,sir.But I wonder that I s there any way that I can color the model I've generated?

**Comment by dendenxu** [comment]
Are you referring to the generated mesh of the trained model? 
If it's just for previewing:
- You can query the canonical `render_network` for vertex color or texture colors (possibly use one of the training view directions).
- After that just use your favorite 3D mesh saving library (maybe `open3d`, `trimesh`, or `pytorch3d`) to write the mesh along with its vertex/texture color to disk.
If you want to convert an `anisdf`/`aninerf` model to mesh without any precision/realism loss:
- That would be a research problem on its own!
- For example, you will have to incorporate the view-dependent effect onto the generated mesh, using something like spherical harmonics?
