### ISSUE TITLE
关于变换矩阵的计算

### ISSUE THREAD

**Issue by Maradowei** [zju3dv/animatable_nerf#54]
https://github.com/zju3dv/animatable_nerf/blob/master/tools/render_skeleton.py#L63
请问为什么变换矩阵的偏移可以直接用根节点坐标系下的偏移而不是用上一个节点坐标系下的偏移？

**Comment by dendenxu** [comment]
您好！
L63的偏移并非最终的偏移，在L79我们将其变换为了上一个节点坐标系下的偏移。
同时，该实现是从smplx.lbs.batch_rigid_transform上魔改来的，您也可以参考原始的实现：https://github.com/vchoutas/smplx/blob/main/smplx/lbs.py#L349
