### ISSUE TITLE
question about the way to compute alpha in AniSDF

### ISSUE THREAD

**Issue by 07hyx06** [zju3dv/animatable_nerf#57]
Hi, thanks for the code! Is the 0.005 here the hard-coded distance between adjacent sampled points? What about the result if compute the distance from the `dist` params? Will the training be crashed?

https://github.com/zju3dv/animatable_nerf/blob/e5945195827037b118fc3eed7f86dae3516ef9d2/lib/networks/bw_deform/anisdf_pdf_network.py#L278-L279

**Comment by dendenxu** [comment]
Hi! 
As you've pointed out, this value is empirically chosen and corresponds to the distances between adjacent samples on a single ray from the original NeRF. 
Setting it to the actual distance wouldn't make any difference in our experiments. (I've even tried setting `0.005` to `1`, no significant impact on training or the results)
So we just leave this value hard-coded for simplicity. (In this case, the volume rendering becomes pure alpha blending.)
