### ISSUE TITLE
自制数据集时如何获取animatable_nerf数据集中的'lbs'文件夹下的所有文件呢

### ISSUE THREAD

**Issue by 13136983989** [zju3dv/animatable_nerf#58]
![image](https://github.com/zju3dv/animatable_nerf/assets/42019021/e35561de-7d25-47b6-a56d-d08c8274cd54)

我们昨天在[neuralbody](https://github.com/zju3dv/neuralbody)上问了怎么获取params和vertices的问题，感谢您的及时解答，解决了这个问题。
我们的目标是自建一个可以在[animatable_nerf](https://github.com/zju3dv/animatable_nerf)上使用的类似ZJU_MoCap的数据，我们注意到animatable_nerf需要数据集中`\lbs\`文件夹下包含图片所示的这些文件。这些文件该怎么获取？`lbs\bweights`文件夹下的.npy文件呢？

**Comment by pengsida** [comment]
animatable nerf现在的代码可以不需要lbs\bweights文件夹下的.npy文件了。请查看这个config文件中的代码文件：https://github.com/zju3dv/animatable_nerf/blob/master/configs/aligned_nerf_pdf/aligned_aninerf_pdf_s9p.yaml
