### ISSUE TITLE
Is it possible to synthesize novel poses on trained model(extended version)?

### ISSUE THREAD

**Issue by sunwonlikeyou** [zju3dv/animatable_nerf#59]
First, Thank you for sharing codes!!
I'd like to synthesize novel pose on extended model. Novel pose means like random smpl poses, e.g. aist++ datasets or AMASS. datasets. 

There is a code to retrain blend weights of unseen poses. But There is no code to retrain the unseen poses for extended model and also that code seems like training for novel frames. 

How can I synthesize totally unseen poses?

**Comment by pengsida** [comment]
You could revise the pose parameters here: https://github.com/zju3dv/animatable_nerf/blob/master/lib/datasets/tpose_pdf_pose_sequence_dataset.py#L99

**Comment by pengsida** [comment]
No. Our model generalizes to various human poses. Here are some results on difficult poses: https://zju3dv.github.io/animatable_sdf/

**Comment by sunwonlikeyou** [comment]
In your paper, and https://github.com/zju3dv/animatable_nerf/issues/46 
Do I have to retrain novel poses?? and is it okay without RGB and masks?

**Comment by pengsida** [comment]
The extended version does not require the re-training, while the ICCV version needs it.

**Comment by sunwonlikeyou** [comment]
Then, there is no problem just revising the config file

vertices: 'vertices'
params: 'params'

these are something novel poses like amass or aist??

**Comment by sunwonlikeyou** [comment]
I'm so sorry but Can I get a novel pose and pretrained model??
I mean some poses and pretrained avatars in https://zju3dv.github.io/animatable_sdf/

**Comment by TT-T1** [comment]
Hi, 
hello, have you achieved success?
