### ISSUE TITLE
question about novel pose generation in SDF-PDF

### ISSUE THREAD

**Issue by pixiaonuo** [zju3dv/animatable_nerf#60]
I want to use the SDF-PDF version to generate images of the human body in a novel pose. I only input the new pose parameters, which will result in distorted results. I found that it is necessary to generate 6890 vertex coordinates in SMPL corresponding to the new pose, but how can I generate the vertex coordinates of the novel pose?

**Comment by dendenxu** [comment]
Hi @pixiaonuo, the 6890 vertices are results of forwarding the 72(24*3) human poses through the SMPL model. You could generate those vertices using [easymocap](https://github.com/zju3dv/EasyMocap) (we normally use this) or the original [smplx](https://github.com/vchoutas/smplx) repo. The output could be converted to aninerf/neuralbody format following this comment: https://github.com/zju3dv/neuralbody/issues/137#issuecomment-1545066167. It's essentially storing the vertices as a frame-number-named npy files under the vertices folder and storing SMPL parameters as npys in the params folder. 

Hope this solves your problem. Feel free to reply if you have any further questions!

**Comment by pixiaonuo** [comment]
Thank you for your reply. I haven't thought about collecting data myself yet. I now want to generate novel poses on your publicly available zju mocap dataset. The novel pose was obtained from the AMASS dataset. So how can I obtain the 6890 vertices of the novel pose in the zju mocap dataset to generate the npy file?

**Comment by dendenxu** [comment]
I assume you want to train a model using the ZJU-MoCap dataset and then render it using poses from amass right?
If that's the case, you should first perform training using the provided dataset and then prepare another dataset where all pose related parameters (the `lbs` `params` and `vertices` folder) are replaced with ones that correspond with your novel poses.

**Comment by xianrui-luo** [comment]
> Hi @pixiaonuo, the 6890 vertices are results of forwarding the 72(24*3) human poses through the SMPL model. You could generate those vertices using [easymocap](https://github.com/zju3dv/EasyMocap) (we normally use this) or the original [smplx](https://github.com/vchoutas/smplx) repo. The output could be converted to aninerf/neuralbody format following this comment: [zju3dv/neuralbody#137 (comment)](https://github.com/zju3dv/neuralbody/issues/137#issuecomment-1545066167). It's essentially storing the vertices as a frame-number-named npy files under the vertices folder and storing SMPL parameters as npys in the params folder.
> 
> Hope this solves your problem. Feel free to reply if you have any further questions!

Hi I use easymocap to get the smpl, but the pose is of the shape[1,69]. Is it supposed to be [1,72]?
