### ISSUE TITLE
Per-subject scores of ZJU-Mocap and Ckpts for the other five subjects

### ISSUE THREAD

**Issue by ChenYutongTHU** [zju3dv/animatable_nerf#63]
Thanks for the repo!

1. Can you provide per-subject scores on ZJU-MoCap of novel-pose and novel-view settings? I can only find the average scores in your paper.
2. Could you please release checkpoints for the other five subjects. There are only 4 subjects' ckpt [here](https://drive.google.com/drive/folders/1KdER2gM4rdPjK_GX_PylAxv3xViMSIUS).

Great thanks!

**Comment by pengsida** [comment]
We have presented the results in the TPAMI version of Neural Body: https://ieeexplore.ieee.org/document/10045794

![image](https://github.com/zju3dv/animatable_nerf/assets/11582122/ca3f857f-c384-49e3-9ff5-fc178e2ef6ec)

**Comment by pengsida** [comment]
This is all of our models presented in the TPAMI version of Ani-NeRF: https://zjueducn-my.sharepoint.com/:f:/g/personal/3180105504_zju_edu_cn/EviTtaiXd5xFkCPq7bslKTgB_gwRzxmpp7iCHIkEPeriwA?e=olLw2S
