### ISSUE TITLE
Number of cameras in ZJU-Mocap

### ISSUE THREAD

**Issue by ChenYutongTHU** [zju3dv/animatable_nerf#64]
Hi authors,

Great thanks for the repo.
The paper mentions ZJU-Mocap has 21 cameras and 4 out of them are used for training for the multi-view setting.

However, in the downloaded ZJU dataset, I found there were 23 cameras in total. [Camera 1 to Camera 23]

Could you help clarify which cameras you use for training and test?

Great thanks!

Best,
Yutong

**Comment by pengsida** [comment]
Please read the config file.
