### ISSUE TITLE
How to render normal image

### ISSUE THREAD

**Issue by whao22** [zju3dv/animatable_nerf#67]
Hi, thanks for your interesting work, and how can i do to render normal image by your code?

**Comment by whao22** [comment]
i have found the answer in [ARAH](https://github.com/taconite/arah-release)

**Comment by JiatengLiu** [comment]
hello @whao22 , I can not find the script of how to render normal image, could you tell me how to do that? Thanks;)

**Comment by whao22** [comment]
> hello @whao22 , I can not find the script of how to render normal image, could you tell me how to do that? Thanks;)

You can refer to the code from lines 228 to 313 in this [script](https://github.com/taconite/arah-release/blob/main/im2mesh/metaavatar_render/models/__init__.py).

**Comment by JiatengLiu** [comment]
thanks for you reply! and by the way, have you successfully get the rendered normal map? When I try to run my scripts and I encountered the following problems.
```
ModuleNotFoundError: No module named 'pytorch3d.utils.cameras_from_opencv_projection'
```

**Comment by whao22** [comment]
> thanks for you reply! and by the way, have you successfully get the rendered normal map? When I try to run my scripts and I encountered the following problems.
> 
> ```
> ModuleNotFoundError: No module named 'pytorch3d.utils.cameras_from_opencv_projection'
> ```

You should correctly install `pytorch3d` library following [this tutorial](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md).

**Comment by JiatengLiu** [comment]
I have fixed this error, thanks for your reply!



At 2024-07-08 18:46:57, "Hao Wang" ***@***.***> wrote:

thanks for you reply! and by the way, have you successfully get the rendered normal map? When I try to run my scripts and I encountered the following problems.

ModuleNotFoundError: No module named 'pytorch3d.utils.cameras_from_opencv_projection'


You should correctly install pytorch3d library following this tutorial.
