### ISSUE TITLE
Hello, the URL of the pre-trained model you provided cannot be opened.

### ISSUE THREAD

**Issue by ZxyLinkstart** [zju3dv/animatable_nerf#7]

**Comment by pengsida** [comment]
Yes. I found that there are some problems in synthesizing novel views with pre-trained models. I need to find the bug in the code.

**Comment by ZxyLinkstart** [comment]
> Yes. I found that there are some problems in synthesizing novel views with pre-trained models. I need to find the bug in the code.

Ok, thank you

**Comment by pengsida** [comment]
I have fixed the bug and uploaded the pretrained models.
