### ISSUE TITLE
能否使用ZJU_MOCAP数据集训练

### ISSUE THREAD

**Issue by Auggst** [zju3dv/animatable_nerf#8]
您好，感谢您的开源。

刚申请Human3.6M数据集还没有得到回复。我想问一下：
1. 能否用ZJU_MOCAP数据集训练？
2. 如果可以，ZJU_MOCAP数据集缺少lbs相关内容，如何获取呢?

**Comment by pengsida** [comment]
1. 可以用zju-mocap数据集训练。
2. 我只处理了zju-mocap的4个subjects。这是数据集的链接：https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/EsCahURVXs1Gm6Oe-sF9zFABWwOLblFd_dP0Ovh8NN2d9w?e=L8P7B0
